export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const REMOVE = 'REMOVE';

export const CREATE_REVIEW_WITH_USER = 'CREATE_REVIEW_WITH_USER';
export const CREATE_REVIEW = 'CREATE_REVIEW';
export const CREATE_USER = 'CREATE_USER';

export const CHANGE_RESTAURANT = 'CHANGE_RESTAURANT';

export const ADD_REVIEW_ID_TO_RESTAURANT = 'ADD_REVIEW_ID_TO_RESTAURANT';
